### ISSUE TITLE
Add nvmrc and documentation on using it in CONTRIBUTING

### ISSUE THREAD

**Issue by bradtaniguchi** [bradtaniguchi/es6-timed-map#14]
Add a `.nvmrc` file and documentation on using this for local development in contributing.

a doc on how this works: https://medium.com/@faith__ngetich/locking-down-a-project-to-a-specific-node-version-using-nvmrc-and-or-engines-e5fd19144245

**Comment by saravananselvamohan** [comment]
@bradtaniguchi . Would like to work on this issue
