### ISSUE TITLE
Finalize support for hacktober

### ISSUE THREAD

**Issue by bradtaniguchi** [bradtaniguchi/es6-timed-map#15]
I'm pretty sure I missed doing a few things to setup this repo for hacktoberfest. If you have any ideas add them below!

**Comment by nhcarrigan** [comment]
Should create a `hacktoberfest-accepted` label to apply to valid PRs that aren't merged (or won't be merged in time for the event).

**Comment by bradtaniguchi** [comment]
Ok I'll add the label, I should be active enough keep up for now, but adding it now will mean one less thing later :+1: 

thanks :D

**Comment by bradtaniguchi** [comment]
Hacktober has finished, so going to start cleaning up some stuff in this repo.

Thank you for all of those that participated :D

**Comment by bradtaniguchi** [comment]
got side tracked for bit, but closing this as I think everything is cleaned up. Going to get the package setup on npm, and updating everything else. Along with continuing with finalizing the api :)
