### ISSUE TITLE
[Enhancement] finalize what the _timers typing is

### ISSUE THREAD

**Issue by bradtaniguchi** [bradtaniguchi/es6-timed-map#18]
Right now the _timers typedef is:
```ts
_timers = new Map<K, NodeJS.Timeout | number>();
```

I'm not sure if this is ok for browser support, or is even right. Need more testing and playing around with it.

**Comment by ValentiMS** [comment]
In order to add #30, the timer should also store the callback function. Maybe something like
```ts
type TimeoutID = NodeJS.Timeout | number;
type Timer<K, V> = [TimeoutID, (key: K, value: V) => any];

```
would work.

**Comment by bradtaniguchi** [comment]
@ValentiMS I think I understand where your going with saving the callback passed.

I want to go over how I think this feature needs to work, just in case there is an easier way. I mostly glossed over any implementation info in the original post since I was in a rush too haha.

So the only way to "update" a `setTimeout` is use `clearTimeout` on the `NodeJS.Timeout | number` returned from the `setTimeout`. Once cleared, we need to set the "new" `setTimeout` hence the need to save the callback. 

If thats the right way to go about it then we can update the map with the type you provided :+1:

**Comment by ValentiMS** [comment]
Great! :+1: 
Further changes will need to be made to the Timer type to support #32  . The UNIX epoch of the timer creation time should also be stored to tell how much time is left.

Maybe an interface instead of a tuple would be more ergonomic?

**Comment by bradtaniguchi** [comment]
We can always change it around if there is an issue comes up later with the existing types. :)

**Comment by bradtaniguchi** [comment]
Closed with the above commit
