### ISSUE TITLE
[Chore] Add readme badges

### ISSUE THREAD

**Issue by bradtaniguchi** [bradtaniguchi/es6-timed-map#2]
Add readme badges, similar to:

```
![Issues](https://img.shields.io/github/issues/bradtaniguchi/es6-timed-map)
![PRs](https://img.shields.io/github/issues-pr/bradtaniguchi/es6-timed-map)
```

Do it later once the actual code is setup and there are issues/prs

**Comment by LandonLloyd** [comment]
I can do this one! Just tell me which badges you want.

**Comment by bradtaniguchi** [comment]
@LandonLloyd you can add any number you want, just make sure they all have the same "theme", and keep em the top of the page and we can add/remove if they work out or not.

General suggestions I have would be
- license (MIT)
- languages (TypeScript)
- tested
- hacktoberfest (? idk if this exists, but should haha)

In the future we have some other ones
- npm
- version
- test coverage

**Comment by LandonLloyd** [comment]
Ok. Let me do some homework rlly quick then I can get to this.
