### ISSUE TITLE
[Chore] Update repo to meet some of the cc-open-source github 

### ISSUE THREAD

**Issue by bradtaniguchi** [bradtaniguchi/es6-timed-map#34]
We can update the repo to meet the creative commons opens source guidelines. **I think this might be pure overkill**, but it would be a good learning experience :)

- [ ] add `./cc-metadata.yml` file [see](https://opensource.creativecommons.org/contributing-code/github-repo-guidelines/#cc-metadata-file)
- [ ] update pull request template [see](https://developercertificate.org/)
- [ ] add support resources (?) [see](https://help.github.com/en/articles/adding-support-resources-to-your-project)
  - Currently the only "support" available is to create an issue here. We will create a discord room in the future if there is a need.
- [ ] update labels in repo to standard, [see](https://opensource.creativecommons.org/contributing-code/repo-labels/)
- [ ] update branch protections
 
This is the full checklist:
https://opensource.creativecommons.org/contributing-code/github-repo-guidelines/

**Comment by nhcarrigan** [comment]
I'd be happy to jump in on a few of these. 🙂
