### ISSUE TITLE
[Feature] Add test coverage logic/support with jest

### ISSUE THREAD

**Issue by bradtaniguchi** [bradtaniguchi/es6-timed-map#7]
The basics of jest are setup, but we should have test coverage support provided somehow so we can show it as a badge in the README.md

**Comment by mihmilicio** [comment]
I can do it.... I can create an script (in package.json) that will generate the badge in the coverage folder... Just assign me the issue!

**Comment by bradtaniguchi** [comment]
@mihmilicio Awesome thanks!
